### ISSUE TITLE
Release Drafter is not creating the next release (and updating it)

### ISSUE THREAD

**Issue by dadoonet** [toolmantim/release-drafter#127]
Not sure if I did something wrong but after I have released a new version (2.6) of my project, Release Drafter does not seem to create a draft for the next release (2.7) although I'm merging PRs.

May be my configuration file is incorrect? Is there any way to have some logs?

```
name-template: v$NEXT_PATCH_VERSION 🌈
tag-template: v$NEXT_PATCH_VERSION
categories:
  - title: 🚀 New features
    label: new
  - title: 🚨 Bug Fixes
    label: bug
  - title: 💉 Updated features
    label: update
  - title: 🧹 Cleaned or removed features
    label: remove
  - title: 📝 Documentation updates
    label: doc
  - title: 🚦 Tests
    label: test
change-template: - #$NUMBER: $TITLE (thanks to @$AUTHOR)
template: |
  ## What's Changed

  $CHANGES

  ## Thanks to

  $CONTRIBUTORS

```

My project lives at: https://github.com/dadoonet/fscrawler
The new milestone I'm working on: https://github.com/dadoonet/fscrawler/milestone/24?closed=1

Here is what I can see in the releases section:

![image](https://user-images.githubusercontent.com/274222/51976591-5a8dbf00-2485-11e9-9c3d-989e1f07da59.png)
