### ISSUE TITLE
Excess Old Pulls & Issues

### ISSUE THREAD

**Issue by ivan-nginx** [toolmantim/release-drafter#217]
## Config

https://github.com/theme-next/hexo-theme-next/blob/master/.github/release-drafter.yml

```yml
# Configuration for Release Drafter - https://github.com/toolmantim/release-drafter

name-template: 'v$NEXT_MINOR_VERSION'
tag-template: 'v$NEXT_MINOR_VERSION'
categories:
  - title: '💥 Breaking Changes'
    label: '💥 Breaking Change'

  - title: '🌀 External Changes'
    label: '🌀 External Change'

  - title: '🌟 New Features'
    label: '🌟 New Feature'

  - title: '⭐ Features'
    label: '⭐ Feature'

  - title: '🛠 Improvements'
    label: '🛠 Improvement'

  - title: '🐞 Bug Fixes'
    label: '🐞 Bug Fix'

  - title: '📖 Documentation'
    label: '📖 Docs'

  - title: '🌍 Localization'
    label: '🌍 i18n'

change-template: '- $TITLE (#$NUMBER)'
no-changes-template: '- No changes'
template: |
  $CHANGES
  ***
  For full changes, see the [comparison between $PREVIOUS_TAG and v$NEXT_MINOR_VERSION](https://github.com/theme-next/hexo-theme-next/compare/$PREVIOUS_TAG...v$NEXT_MINOR_VERSION)

```

## Problem

![image](https://user-images.githubusercontent.com/16944225/58276274-890e0d80-7d86-11e9-8080-800b743c1a3d.png)

[Issue #25](https://github.com/theme-next/hexo-theme-next/issues/25) and [Pull #22](https://github.com/theme-next/hexo-theme-next/pull/22) was closed in 2018. As we can see, at least pulls under ≈800x numbers can be included, not ≈100x.

## Possible solution

In previous month that bug wasn't appear as I remember. Also, emoji on labels wasn't used before, maybe some conflict here.
