### ISSUE TITLE
Categories: Add support of multiple labels per category

### ISSUE THREAD

**Issue by oleg-nenashev** [toolmantim/release-drafter#218]
I am working on a global Release Drafter configuration in https://github.com/jenkinsci . The organization contains numerous repositories which use different tags due to historical reasons. I am interested to streamline labeling in our repositories, but it will take a while. 

For example, this is a configuration for bugfix tags:

```yaml
categories:
  - title: 🐛 Bug Fixes
    label: bug
  - title: 🐛 Bug Fixes
    label: fix
  - title: 🐛 Bug Fixes
    label: bugfix
  - title: 🐛 Bug Fixes
    label: regression  
```

From a UX perspective, it would be great to have support of multiple labels definition, e.g.

```yaml
categories:
  - title: 🐛 Bug Fixes
    labels: 
      - bug
      - fix
      - bugfix
      - regression  
```
