### ISSUE TITLE
Add support of generating machine-readable changelogs (YAML?)

### ISSUE THREAD

**Issue by oleg-nenashev** [toolmantim/release-drafter#253]
As a maintainer, I would be interested to generate a machine-readable changelog in addition to user release notes.

Currently Release Drafter targets Markdown as a destination format. In the case of the Jenkins project, we maintain a machine readable changelog in YAML so that we can later generate https://jenkins.io/changelog/ and other data sources. Raw data: https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml

Currently the changelog is generated using automation scripts, but it would be great to use Release Drafter.

What would I expect from YAML generation:

* Being able to use replacer-alike approach to extract data from the message and to inject YAML fields
* Simplified generation of the YAML output syntax

### Workaround 

I was able to hack a workaround using non-trivial replacers to extract issue numbers and to put them into YAML.

Configuration:

```
# Configuration for Release Drafter: https://github.com/toolmantim/release-drafter
name-template: $NEXT_PATCH_VERSION
# Uses a more common 2-digit versioning in Jenkins weekly releases.
version-template: $MAJOR.$MINOR
tag-template: jenkins-$NEXT_MINOR_VERSION

# TODO: categories are YAGNI for now, until we can extract `type` somehow
exclude-labels:
  - reverted
  - no-changelog
  - skip-changelog
  - invalid
change-template: |-
  - type: todo
    message: |-
      $TITLE
    pull: $NUMBER
    authors:
      - $AUTHOR
template: |
  '''yaml
  $CHANGES
  '''
replacers:
  - search: '/\[*JENKINS-(\d+)\]*\s*-*\s*/g'
    replace: |-
      issue: $1
        message: |-
          
  - search: |-
      message: |-
          issue:
    replace: "issue:"
```

Generated output:

![ReleaseDrafter_YAML](https://user-images.githubusercontent.com/3000480/60585000-fa31df00-9d8e-11e9-8e9a-ed4edaa2758e.PNG)
