### ISSUE TITLE
Draft release adds old PRs, also increments NEXT_PATCH_VERSION incorrectly

### ISSUE THREAD

**Issue by jonathanstegall** [toolmantim/release-drafter#263]
Hello,

I'm referring to this repository here: https://github.com/MinnPost/object-sync-for-salesforce/

Here's my release-drafter.yml:

```yml
name-template: Version $NEXT_PATCH_VERSION 🌈
tag-template: v$NEXT_PATCH_VERSION
categories:
  - title: 🚀 Features
    label: feature
  - title: 🐛 Bug Fixes
    label: bug fix
  - title: 🧰 Maintenance
    label: chore
  - title: 💻 For Developers
    label: for developers
change-template: '- $TITLE (#$NUMBER)'
template: |
  $CHANGES
```

The current tag/version on this repo is Version 1.8.6, but a new merged pull request in master instead generates 1.84.1.

1.8.6 had the following contents:

![image](https://user-images.githubusercontent.com/435342/61655145-8e52e000-ac83-11e9-9a1f-4ec30f9335ea.png)

But here, 1.84.1 has duplicated most of these items:

![image](https://user-images.githubusercontent.com/435342/61655177-a296dd00-ac83-11e9-9c21-8bb080d6aa20.png)

So it adds new things, but it maintains older things as well.

I thought maybe if I deleted the draft and tried again it would fix, but this was not the case.
