### ISSUE TITLE
Release Drafter doesn't work, labels with spaces?

### ISSUE THREAD

**Issue by Remzi1993** [toolmantim/release-drafter#267]
Release Drafter doesn't work, I'm doing something wrong?
This is what I have. Could it be the labels? I have some labels with spaces. Should I change some labels, for example to: code-climate.

https://github.com/Remzi1993/jquery-manager/blob/master/.github/release-drafter.yml
```
name-template: 'jQuery Manager v$NEXT_PATCH_VERSION'
tag-template: '$NEXT_PATCH_VERSION'

categories:
  - title: '🚀 Features'
    labels:
      - 'Feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'Fix'
      - 'Bug'
  - title: '🔒 Security Updates'
    labels:
      - 'Security'
  - title: '🧰 Maintenance'
    label: 'Library'
    label: 'Code Climate'
    label: 'Docs'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

template: |
  # What's changed (changelog)
  $CHANGES
  ## Thanks to
  $CONTRIBUTORS
```

**Comment by casz** [comment]
Ya your yaml is off 😢

```
name-template: 'jQuery Manager v$NEXT_PATCH_VERSION'
tag-template: '$NEXT_PATCH_VERSION'

categories:
  - title: '🚀 Features'
    labels:
      - 'Feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'Fix'
      - 'Bug'
  - title: '🔒 Security Updates'
    labels:
      - 'Security'
  - title: '🧰 Maintenance'
    labels:
      - 'Library'
      - 'Code Climate'
      - 'Docs'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

template: |
  # What's changed (changelog)
  $CHANGES
  ## Thanks to
  $CONTRIBUTORS
```

You need to use `labels:` for multiple and `labels:` or `label:` for singular.
